export const tableData = [
    {
      id: 1,
      id: 101,
      name: "Kim Namjoon",
      date: "07/11/2020",
      description: "Travel Expense",
      amount: "1000",
      status: "Accepted",
    },
    {
        id: 2,
        id: 102,
        name: "Kim Seokjin",
        date: "08/11/2020",
        description: "Food Expense",
        amount: "2000",
        status: "Accepted",
    },
    {
        id: 3,
        id: 103,
        name: "Min Yoongi",
        date: "09/11/2020",
        description: "Transport Expense",
        amount: "5000",
        status: "Rejected",
    },
    {
        id: 4,
        id: 104,
        name: "Jung Hoseok",
        date: "10/11/2020",
        description: "Vehicle Expense",
        amount: "9000",
        status: "Accepted",
    },
    {
        id: 5,
        id: 105,
        name: "Park Jimin",
        date: "11/11/2020",
        description: "Rental Expense",
        amount: "12000",
        status: "Rejected",
    },
    {
        id: 6,
        id: 106,
        name: "Kim Taehyung",
        date: "12/11/2020",
        description: "Food Expense",
        amount: "8000",
        status: "Accepted",
    },
    {
        id: 7,
        id: 107,
        name: "Jeon Jungkook",
        date: "14/11/2020",
        description: "Travel Expense",
        amount: "6000",
        status: "Rejected",
    },
  ];